### ISSUE TITLE
Define proper `build` or `run` type for dependencies in DAQ packages' `package.py`

### ISSUE THREAD

**Issue by dingp** [DUNE-DAQ/daq-release#129]
Defining proper `run` or `build` type of a dependency helps to minimize the number of packages loaded by spack. It also helps to get a precise set of packages needed for the running environment. This will help to produce a slimmer docker image for running, which will be very useful for Kubernetes.

To achieve this, we will need to go through all the `depends_on` calls in the release repo templates `package.py` files, and add dependency types to the `depends_on` call. The `depends_on` entries in umbrella packages' package.py files are generated from release YAML files. The YAML file will need to have an additional attribute (e.g. `dependent_type`) for each of the external dependency, and DAQ package.

Even if a dependency meets all the types of `run`, `build`, `link`, it helps to put `type=('build', 'link', 'run')`explicitly in the `depends_on` call. 

Some examples:

In `daq-release/spack-repos/externals/packages/devtools/package.py`

```python
depends_on("cmake@3.21.4")
```
will be replaced by

```python
depends_on("cmake@3.21.4", type='build')
```

In `daq-release/spack-repos/release-repo-template/packages/externals/package.py`

```python
depends_on("devtools@XRELEASEX")
```
will be replaced by

```python
depends_on("devtools@XRELEASEX", type='build')
```

For the release YAML file, the changes will be like the following:

```yaml
        - name: boost
          version: 1.73.0
          variant: "+context+container cxxstd=17"
```

will be changed into:

```yaml
        - name: boost
          version: 1.73.0
          variant: "+context+container cxxstd=17"
          dependent_type: ['run', 'build', 'link']
```

Additionally, the `make-release-repo.py` script needs update to parse the `dependent_type` attribute, **especially convert the python list into tuple since YAML does not support tuple type but list type only**, and add them to the `depends_on` entries.
