### ISSUE TITLE
Reorganize release manifest file with the introduction of umbrella (bundle) packages

### ISSUE THREAD

**Issue by dingp** [DUNE-DAQ/daq-release#2]
As discussed in issue [#36](https://github.com/DUNE-DAQ/daq-buildtools/issues/36) in `daq-buildtools`, we are exploring the umbrella packages.

With the introduction of umbrella packages, the "release manifest file" is a bit redundant for setting up a user's development environment, as the umbrella package tracks all the dependent packages.

However, the release manifest file is still valuable and it will just have its role moved to the back of the stage. It can help with generating the umbrella package. Below is a proposed reorganization of the release manifest file for this purpose.

It maps to the proposed directory structure in cvmfs as discussed in #1. 

```yaml
---
    # Release tag, in the format of vX.X.X or "development"
    # "vX.X.X" should be the actual tag used in other DAQ git repos.

    release: v1.1.0

    product_paths:
        - /cvmfs/dune.opensciencegrid.org/dunedaq/DUNE/products

    release_path:
        - /cvmfs/dune.opensciencegrid.org/dunedaq/DUNE/releases-tmp

    # List of all external dependencies provided by 3rd parties (e.g. SciSoft).

    externals:
        - name: ninja
          version: v1_10_0
          variant: ~
        - name: cmake
          version: v3_17_2
          variant: ~
        - name: cetlib
          version: v3_10_00
          variant: e19:prof
        - name: TRACE
          version: v3_15_09
          variant: ~
        - name: folly
          version: v2020_05_25
          variant: e19:prof
        - name: nlohmann_json
          version: v3_9_0b
          variant: e19:prof

    # List of DAQ's prebuilt packages in UPS products area; this is for DAQ
    # packages typically built by developers in their working directory.
    
    packages:
        - name: ers
          version: v0_26_00c
          variant: "e19:prof"

```
