### ISSUE TITLE
New user's yaml file defining working environment

### ISSUE THREAD

**Issue by dingp** [DUNE-DAQ/daq-release#5]
With the introduction of release umbrella package, a release manifest file is no longer needed by a user for setting up the working environment; the user's manifest file itself is sufficient.

Below is a proposed format of the user's yaml file defining most if not all the info needed for setting up a working environment. The goal is to have this yaml file together with a parser script to replace all configurable part of the `quick-start.sh` (and the setup/build script it generates).

```yaml
---
    comments: "Something to comment, ignored by the parser script."

    base_release: develop

    product_paths: ~

    externals: ~

    packages: ~

    repos: ~
        
    workdirs:
        - build: ./build
        - log: ./log
        - install: ./install
        - source: ./sourcecode

```
