### ISSUE TITLE
patch `cpr` to have proper cmake config file (with targets generated) before moving to products

### ISSUE THREAD

**Issue by dingp** [DUNE-DAQ/daq-release#9]
The UPS product of `cpr` has been created. The build script is in this repo. The product is put under `products_dev` area at the moment.

The `cpr-config.cmake` came with the package use the find module style, which does not have targets created. Users will need to use something similar to the following in their CMakeLists.txt file.

```
find_package(cpr)
target_link_libraries(your_pkg_src ${CPR_LIBRARIES})
target_include_directories(your_pkg_src ${CPR_INCLUDE_DIRS})
```

If we decide to move `cpr` into `products` in the future, we will need to patch the package to have proper cmake config files generated.

**Comment by dingp** [comment]
Request from Roland and Yann:

We realized that we can't link against the lib, because it has missing link target for CURL functions:
```
session.cpp:(.text+0x1ac): undefined reference to `curl_slist_append'
session.cpp:(.text+0x318): undefined reference to `curl_easy_setopt'
session.cpp:(.text+0x32a): undefined reference to `curl_slist_free_all'
/cvmfs/dune.opensciencegrid.org/dunedaq/DUNE/products_dev/cpr/v1_5_2/Linux64bit+3.10-2.17-e19-prof/lib64/libcpr.a(session.cpp.o): In function `cpr::Session::Impl::SetAuth(cpr::Authentication const&)':
session.cpp:(.text+0x455): undefined reference to `curl_easy_setopt'
/cvmfs/dune.opensciencegrid.org/dunedaq/DUNE/products_dev/cpr/v1_5_2/Linux64bit+3.10-2.17-e19-prof/lib64/libcpr.a(session.cpp.o): In function `cpr::Session::Impl::SetDigest(cpr::Digest const&)':
session.cpp:(.text+0x4b5): undefined reference to `curl_easy_setopt'
/cvmfs/dune.opensciencegrid.org/dunedaq/DUNE/products_dev/cpr/v1_5_2/Linux64bit+3.10-2.17-e19-prof/lib64/libcpr.a(session.cpp.o): In function `cpr::Session::Impl::SetPayload(cpr::Payload&&)':
```

In DAQling, we had similar issues, and we build CPR with the following CMake flags (use system curl, and -fPIC, also without tests.):
```
- name: Run cmake3 in cpr
  cmake: 
    source_dir: /opt/cpr
    binary_dir: /opt/cpr/build
    target: cpr
    build_type: Release
    executable: /usr/bin/cmake3
    cache_vars: {"USE_SYSTEM_CURL": "ON", "BUILD_CPR_TESTS": "OFF", "CMAKE_CXX_FLAGS": "-fPIC"}
```
Can you please help us pushing a new version and new build of CPR with these build flags?
